### ISSUE TITLE
Contactmanagement interrupts Fullscreen-Mode

### ISSUE THREAD

**Issue by Simsen3142** [eProtectioneers/ProjectPanacea#2] opened 2017-05-12 11:19 UTC
If you change the Center-Panel to a ContactPanel, the FullscreenMode is blocked.
Everytime, you try to switch back into FullScreen, the Fullscreen Icon changes again immediately and the Screen isn't fixed anymore.

**Comment by sojournercntl** [comment] 2017-05-12 13:35
Fixed with the last commit! Caused by problems with high DPI Resolution... **used external manifest** 👍

**Closed as completed by sojournercntl** 2017-05-12 13:35 UTC
